In [3]:
##### Import necessary labraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
### Load the dataset
crimes_df = pd.read_csv('crimes_against_women_2001-2014.csv')

In [5]:
### Reading the csv file
crimes_df

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0

In [6]:
#### checking columns names
crimes_df.columns

Index(['Unnamed: 0', 'STATE/UT', 'DISTRICT', 'Year', 'Rape',
       'Kidnapping and Abduction', 'Dowry Deaths',
       'Assault on women with intent to outrage her modesty',
       'Insult to modesty of Women', 'Cruelty by Husband or his Relatives',
       'Importation of Girls'],
      dtype='object')

In [7]:
#### checking rows
crimes_df.index

RangeIndex(start=0, stop=10677, step=1)

In [8]:
##### Find out the shape our dataset
crimes_df.shape

(10677, 11)

#### Data Preprocessing And Cleaning

In [9]:
#### Checking the null or missing values
overall_crime = crimes_df.isna().sum()
overall_crime

Unnamed: 0                                             0
STATE/UT                                               0
DISTRICT                                               0
Year                                                   0
Rape                                                   0
Kidnapping and Abduction                               0
Dowry Deaths                                           0
Assault on women with intent to outrage her modesty    0
Insult to modesty of Women                             0
Cruelty by Husband or his Relatives                    0
Importation of Girls                                   0
dtype: int64

##### Unique districts where crimes has been commited

In [10]:
districts = len(crimes_df.DISTRICT.unique())
districts

1605

##### But there are 718 districts in India, in total, which means there is messy or false datas in a huge amount, in this case, we better drop the column "District" and also "Unnamed: 0", as it is of no use, in our data analysis process.

In [11]:
crimes_df.drop(['DISTRICT', 'Unnamed: 0'], axis = 1, inplace=True)

In [12]:
##### Rename columns with shorter names
crimes_df.rename( columns = {'Kidnapping and Abduction':'Kidnapping_Abduction','Dowry Deaths':'Dowry_Deaths',
                             'Assault on women with intent to outrage her modesty':'Hurting_of_womens_modesty',
                             'Insult to modesty of Women':'Insult_to_womens_modesty',
                             'Cruelty by Husband or his Relatives':'Domestic_Cruelty',
                             'Importation of Girls':'Importation_of_Girls'}, inplace = True)

In [13]:
#### Set to display all columns
pd.set_option('display.max_row', None)

In [14]:
#### Check the new dataset with new names
crimes_df.head(100)

,STATE/UT,Year,Rape,Kidnapping_Abduction,Dowry_Deaths,Hurting_of_womens_modesty,Insult_to_womens_modesty,Domestic_Cruelty,Importation_of_Girls
0,ANDHRA PRADESH,2001,50,30,16,149,34,175,0
1,ANDHRA PRADESH,2001,23,30,7,118,24,154,0
2,ANDHRA PRADESH,2001,27,34,14,112,83,186,0
3,ANDHRA PRADESH,2001,20,20,17,126,38,57,0
4,ANDHRA PRADESH,2001,23,26,12,109,58,247,0
5,ANDHRA PRADESH,2001,0,0,0,1,0,0,0
6,ANDHRA PRADESH,2001,54,51,7,139,129,378,0
7,ANDHRA PRADESH,2001,37,39,24,118,27,746,0
8,ANDHRA PRADESH,2001,56,49,62,414,81,224,0
9,ANDHRA PRADESH,2001,47,30,17,180,336,172,0
10,ANDHRA PRADESH,2001,37,21,10,208,72,265,0
11,ANDHRA PRADESH,2001,29,47,13,141,107,92,0
12,ANDHRA PRADESH,2001,59,27,14,176,41,69,0
13,ANDHRA PRADESH,2001,35,20,26,100,25,192,0
14,ANDHRA PRADESH,2001,35,19,31,188,59,214,0
15,ANDHRA PRADESH,2001,46,80,10,207,228,287,0
16,ANDHRA PRADESH,2001,21,21,19,55,15,228,0
17,ANDHRA PRADESH,2001,19,12,5,140,100,119,0
18,ANDHRA PRADESH,2001,72,83,37,113,55,421,7
19,ANDHRA PRADESH,2001,0,0,1,0,1,0,0
20,ANDHRA PRADESH,2001,8,12,6,38,47,108,0
21,ANDHRA PRADESH,2001,25,48,2,84,122,520,0
22,ANDHRA PRADESH,2001,1,0,0,1,1,0,0
23,ANDHRA PRADESH,2001,12,12,3,67,48,99,0
24,ANDHRA PRADESH,2001,13,6,0,33,462,204,0
25,ANDHRA PRADESH,2001,8,2,0,40,22,121,0
26,ANDHRA PRADESH,2001,53,25,52,241,0,165,0
27,ANDHRA PRADESH,2001,61,21,15,246,56,348,0
28,ANDHRA PRADESH,2001,871,765,420,3544,2271,5791,7
29,ARUNACHAL PRADESH,2001,1,2,0,3,0,0,0
30,ARUNACHAL PRADESH,2001,2,4,0,4,0,2,0
31,ARUNACHAL PRADESH,2001,2,5,0,5,0,0,0
32,ARUNACHAL PRADESH,2001,0,2,0,0,0,0,0
33,ARUNACHAL PRADESH,2001,2,6,0,8,0,0,0
34,ARUNACHAL PRADESH,2001,9,5,0,6,0,3,0
35,ARUNACHAL PRADESH,2001,5,7,0,7,0,2,0
36,ARUNACHAL PRADESH,2001,2,5,0,3,0,0,0
37,ARUNACHAL PRADESH,2001,4,10,0,25,2,2,0
38,ARUNACHAL PRADESH,2001,2,5,0,4,0,0,0
39,ARUNACHAL PRADESH,2001,2,1,0,8,0,2,0
40,ARUNACHAL PRADESH,2001,1,0,0,5,1,0,0
41,ARUNACHAL PRADESH,2001,1,3,0,0,0,0,0
42,ARUNACHAL PRADESH,2001,33,55,0,78,3,11,0
43,ASSAM,2001,28,88,10,29,0,95,0
44,ASSAM,2001,20,21,1,22,0,26,0
45,ASSAM,2001,0,0,0,0,0,0,0
46,ASSAM,2001,45,74,7,80,0,216,0
47,ASSAM,2001,48,47,9,56,0,37,0
48,ASSAM,2001,42,20,0,26,0,0,0
49,ASSAM,2001,43,51,5,49,0,111,0
50,ASSAM,2001,35,37,3,41,0,19,0
51,ASSAM,2001,1,0,0,0,0,0,0
52,ASSAM,2001,35,35,1,54,0,64,0
53,ASSAM,2001,30,40,0,23,0,26,0
54,ASSAM,2001,37,64,5,67,0,98,0
55,ASSAM,2001,24,34,2,27,0,28,0
56,ASSAM,2001,42,28,2,44,0,48,0
57,ASSAM,2001,21,65,2,42,0,27,0
58,ASSAM,2001,5,15,4,5,0,8,0
59,ASSAM,2001,33,8,1,9,0,30,0
60,ASSAM,2001,14,12,0,37,0,20,0
61,ASSAM,2001,64,62,0,22,0,93,0
62,ASSAM,2001,23,37,0,6,0,28,0
63,ASSAM,2001,2,4,0,2,0,7,0
64,ASSAM,2001,51,109,1,113,4,132,0
65,ASSAM,2001,30,27,3,16,0,15,0
66,ASSAM,2001,3,0,0,0,0,0,0
67,ASSAM,2001,47,64,0,28,0,0,0
68,ASSAM,2001,53,80,1,43,0,99,0
69,ASSAM,2001,41,48,2,9,0,21,0
70,ASSAM,2001,817,1070,59,850,4,1248,0
71,BIHAR,2001,93,13,11,3,0,50,0
72,BIHAR,2001,0,0,7,11,0,14,0
73,BIHAR,2001,16,4,33,13,2,19,0
74,BIHAR,2001,25,6,0,4,0,2,0
75,BIHAR,2001,34,10,9,0,0,16,0
76,BIHAR,2001,13,7,21,32,0,21,0
77,BIHAR,2001,20,23,17,23,0,54,8
78,BIHAR,2001,10,12,8,7,0,22,0
79,BIHAR,2001,35,9,20,15,0,52,0
80,BIHAR,2001,22,13,23,0,4,29,0
81,BIHAR,2001,8,1,15,0,0,0,0
82,BIHAR,2001,19,16,37,40,0,34,0
83,BIHAR,2001,25,15,26,27,0,24,0
84,BIHAR,2001,13,18,22,0,2,155,0
85,BIHAR,2001,1,0,0,1,0,1,0
86,BIHAR,2001,10,1,16,8,0,15,0
87,BIHAR,2001,6,5,25,0,0,4,0
88,BIHAR,2001,51,20,6,6,0,29,0
89,BIHAR,2001,0,1,0,2,0,0,0
90,BIHAR,2001,5,6,11,6,0,2,0
91,BIHAR,2001,22,16,4,2,1,39,0
92,BIHAR,2001,10,7,6,12,0,5,0
93,BIHAR,2001,11,15,6,3,0,10,0
94,BIHAR,2001,13,11,12,41,0,18,0
95,BIHAR,2001,44,35,37,3,1,47,0
96,BIHAR,2001,11,15,8,0,0,39,0
97,BIHAR,2001,73,25,69,81,0,141,6
98,BIHAR,2001,2,1,0,4,0,1,0
99,BIHAR,2001,40,12,47,14,2,54,0

##### Analysing the datas of the column "STATE/UT", for that let's find out the names of all the states/UT through .unique()

In [15]:
print(crimes_df['STATE/UT'].unique())

['ANDHRA PRADESH' 'ARUNACHAL PRADESH' 'ASSAM' 'BIHAR' 'CHHATTISGARH' 'GOA'
 'GUJARAT' 'HARYANA' 'HIMACHAL PRADESH' 'JAMMU & KASHMIR' 'JHARKHAND'
 'KARNATAKA' 'KERALA' 'MADHYA PRADESH' 'MAHARASHTRA' 'MANIPUR' 'MEGHALAYA'
 'MIZORAM' 'NAGALAND' 'ODISHA' 'PUNJAB' 'RAJASTHAN' 'SIKKIM' 'TAMIL NADU'
 'TRIPURA' 'UTTAR PRADESH' 'UTTARAKHAND' 'WEST BENGAL' 'A & N ISLANDS'
 'CHANDIGARH' 'D & N HAVELI' 'DAMAN & DIU' 'DELHI' 'LAKSHADWEEP'
 'PUDUCHERRY' 'Andhra Pradesh' 'Arunachal Pradesh' 'Assam' 'Bihar'
 'Chhattisgarh' 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh'
 'Jammu & Kashmir' 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh'
 'Maharashtra' 'Manipur' 'Meghalaya' 'Mizoram' 'Nagaland' 'Odisha'
 'Punjab' 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Tripura' 'Uttar Pradesh'
 'Uttarakhand' 'West Bengal' 'A&N Islands' 'Chandigarh' 'D&N Haveli'
 'Daman & Diu' 'Delhi UT' 'Lakshadweep' 'Puducherry' 'Telangana'
 'A & N Islands']

#### From above, there are lot many repeated datas, like some of them are repeated again by using capital letters and some of them have issues with space too, like A&N Islands and also Delhi has been repeated again by mentioning it as Delhi UT

In [16]:
# Fist we will remove all the repeated uppercase values
def remove_uppercase(r):
    r = r['STATE/UT'].strip()
    r = r.upper()
    return r
crimes_df['STATE/UT'] = crimes_df.apply(remove_uppercase, axis=1)

#Now use replace function to replace the other type of repeated datas as dicussed above
crimes_df['STATE/UT'].replace("A&N ISLANDS", "A & N ISLANDS", inplace = True)
crimes_df['STATE/UT'].replace("D&N HAVELI", "D & N HAVELI", inplace = True)
crimes_df['STATE/UT'].replace("DELHI UT", "DELHI", inplace = True)

#### Let's go through the datas now!

In [17]:
crimes_df['STATE/UT'].unique()

array(['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR',
       'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM',
       'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM',
       'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND',
       'WEST BENGAL', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI',
       'DAMAN & DIU', 'DELHI', 'LAKSHADWEEP', 'PUDUCHERRY', 'TELANGANA'],
      dtype=object)

#### Let's check the total number of States+UT

In [18]:
len(crimes_df['STATE/UT'].unique())

36